# Generated by Django 5.0.6 on 2024-07-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userrequest_monthlyexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='minimisingSaving',
            field=models.BooleanField(default=False),
        ),
    ]
